language: node_js

node_js:
  - 10.15.3

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master